### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by MHOOO** [Karasiq/proxyutils#1]
I'm at a loss on how to use this library.

What would be required to connect a SOCKS5 capable software to this socks proxy? I assume I would require to open a port via akka and connect its binary data, correct? Or do I need to map incoming binary data to the case classes ConnectionRequest, HttpRequest, etc.?

**Comment by Karasiq** [comment]
See https://github.com/Karasiq/proxychain/blob/dd7189782c12fb60628b0c945b43cc4330eb5cdd/src/main/scala/com/karasiq/proxychain/app/Boot.scala#L64-L68

**Comment by MHOOO** [comment]
Thanks, that helped!

Here's a simplified example:

```
val port = 1080
val connections = Tcp().bind("localhost", port)
connections runForeach { conn =>
    conn.handleWith(ProxyServer()).foreach {
        case (request, connection) =>
            (addr, port) = getAddrAndPort(request)
            val destConnection = Tcp().outgoingConnection(addr, port)
            val proxy = ProxyServer.withSuccess(connection, request)
            // by joining them, we connect the input of one, to the output of the other and vice versa
            destConnection.join(proxy).run()
    }
}

```
